### ISSUE TITLE
Add support for fetch api

### ISSUE THREAD

**Issue by darylthayilporch** [Raynos/xhr#110]
If fetch api is present use that otherwise fallback to current logic :) this will let us use update https://github.com/yahoo/fetchr and use it in react native

**Comment by darylthayilporch** [comment]
Im willing to work on it, open to others thoughts

**Comment by yoshuawuyts** [comment]
Nah, that should probably be a different package - similar to [nets](https://github.com/maxogden/nets). If XMLHTTPRequest isn't supported by React native than that should be addressed; the strength of `xhr` is that it's minimal and can be embedded for almost no cost; switching context on features would unnecessarily complicate things.

**Comment by naugtur** [comment]
^ what he said ;)

xhr is there to support an API that is close to `request` module from npm and I currently don't see why we would need fetch internally.

If you want to use xhr module in a react native app to have code that you can share with node, it'd make sense to implement a copy that uses fetch. `require('xhr/fetch')`
But I'd rather not rewrite xhr to fetch just because we can - our existing users wouldn't appreciate that.

I honestly recommend using isomorphic-fetch for your usecase, or just sticking with using fetch directly if you're only writing front-end code

**Comment by darylthayilporch** [comment]
good feedback, I actually figured out that XMLHTTPRequest is implemented by react native :p so next time ill make sure something doesn't work before creating tickets all willy nilly. Thanks
