### ISSUE TITLE
Allow global configuration of XHR and XDR constructors

### ISSUE THREAD

**Issue by mmacaula** [Raynos/xhr#60]
Came from conversation in #11, it would be nice to be able to configure the constructors of the XHR and XDR.  From @Raynos: 
```javascript
require('xhr').set({
  XHR: function () { ... },
  XDR: function () { ... }
})
```

**Comment by dominykas** [comment]
Surely you'd also need a `reset` of some sort?

**Comment by Raynos** [comment]
Nope. your mutating the global state of the `xhr` library. It's your responsibility to set it back to the original state.

The use case for `.set()` is to overwrite the `XHR` constructor so that you can globally set some default headers or something.

**Comment by dominykas** [comment]
To restore the original state, one must be aware of what the original state is. Since both `XHR`/`XDR` are private via closure, there is no way to know the original state. Both contain initialization logic (`noop`, `withCredentials`, etc), so either both need to be exposed in public or there is a need to be able to `reset` them (could be done by passing in `null` to `set` - although I'm not sure that's a good contract).

Ofc, a much simpler solution would be to not keep them as global state and to simply move the construction inside the exported method... But we've been through that discussion...

**Comment by naugtur** [comment]
That's why I'd propose this:

```
var xhr = require('xhr')
xhr.internals.XHR = yourXHRmock
```

And that would be compatible with all sorts of mocking libs, like sinon

```
var stub1=sinon.stub(xhr.internals,"XHR")
stub1.restore()
```

**Comment by Raynos** [comment]
@naugtur makes a good suggestion. 

I would recommend `xhr.XHR` and `xhr.XDR` though.

**Comment by naugtur** [comment]
I thought `xhr.XHR` would be confusing for what it actually means.

BTW. Didn't make the PR to ampersand yet, waiting for the discussion to go somewhere.

**Comment by Raynos** [comment]
we can do `xhr.XMLHttpRequest` or `xhr.XDomainRequest` :D thats less confusing.

**Comment by naugtur** [comment]
Ok, one more thing - why XDR at all? If you mock XHR, you will surely mock it with an implementation that is in line with standards and therefore XDR is not needed. Or am I missing something?

**Comment by Raynos** [comment]
that's upto the user to decide. He can mock both or one.
