### ISSUE TITLE
xhr.send inside a try catch block

### ISSUE THREAD

**Issue by Semigradsky** [Raynos/xhr#70]
> To be safe when handling various kinds of links, the `xhr.send` should be inside a try catch block

What do you think about this?
IE throw `Invalid argument` error in different cases: https://www.google.com/search?q=xhr%20ie%20invalid%20argument

**Comment by Raynos** [comment]
:-1: the application developer can try catch on the outside.

**Comment by Semigradsky** [comment]
Then a good idea to specify this in README. I expected that I would be sufficient to check `err` parameter in callback.

From REAME:
> Your callback will be called with an Error if there is an error in the browser that prevents sending the request.

**Comment by naugtur** [comment]
if `xhr.send` throws instead of calling the error callback, it's an invocation error and imho it's correctly thrown.
Also, the case you link to seems to affect IEs 6-7

We would have more to talk about if you could give us an actual case of:
 xhr throws instead of passing error to the callback when it is correctly called but the request fails.

**Comment by Semigradsky** [comment]
I have an example with IE 9 when throwing error, but it looks like the problem occurs from `localhost` address.

Another example, when there are generated errors: when sending sync request with error
https://xhr.spec.whatwg.org/#request-error-steps

**Comment by naugtur** [comment]
If you have it, why not share?

And from the spec I see that the problem only occurs if you're using a synchronous request. So we could consider catching only in that case and deciding if xhr should re-throw or call the error callback.

I'm not convinced that there's a need for it.

**Comment by paddyforan** [comment]
I'm seeing this from the `xhr.send` line when creating a valid request that fails to establish a connection (e.g., the host is down or unreachable). I'm not sure if this qualifies as

> xhr throws instead of passing error to the callback when it is correctly called but the request fails.

or if it's something I should be try/catch-ing for, but it was unexpected behaviour.

I'm also running version 1.17.1, so I don't know if that makes any difference. It seems to be the latest version supported by [ampersand-sync](https://github.com/ampersandjs/ampersand-sync), which is why I don't know if the issue persists against 2.0.1.

![screen shot 2015-05-31 at 5 59 11 pm](https://cloud.githubusercontent.com/assets/59249/7904133/cc7dd2ae-07be-11e5-93ba-28178bc509b3.png)

**Comment by Raynos** [comment]
@paddyforan did you set `sync: true` to make as synchronous XHR request ?

**Comment by paddyforan** [comment]
It's unclear to me why a synchronous XHR request would trigger the error handler, while an asynchronous XHR request would throw an exception, but I'll admit this isn't my area of expertise.

This is what I get when I set "sync: true".

![screen shot 2015-05-31 at 6 51 10 pm](https://cloud.githubusercontent.com/assets/59249/7904385/0eb48580-07c6-11e5-9bac-b3932c3c32b6.png)

**Comment by Raynos** [comment]
@paddyforan 

If you set `sync: true` i would expect `send()` to throw.

It's very strange that `send()` throws for asynchronous http requests :S

**Comment by paddyforan** [comment]
In case anyone is curious, if you check the screenshot, it's me being silly. The requests that are getting blocked are OPTIONS requests, for CORS, which the library has no control over, AFAIK. It seems Chrome just logs all failed CORS requests as errors? Huh.

Anyways, I'm gonna call this one PEBCAK.

**Comment by naugtur** [comment]
Anyway, thanks for posting back!
