### ISSUE TITLE
Add option (or default) to parse option.json and add as URL arguments

### ISSUE THREAD

**Issue by WilliamHolmes** [Raynos/xhr#95]
For GET (and possibly PUT & DELETE), options.json is not automatically added to the URL as parameter arguments. i.e.

xhr({url:'/service', json:{arg1:'foo', arg2:'bar'},function(err, resp, body){ })

/service?arg1=foo&arg2=bar

Most other libraries will do this so it would be great if this npm would also do this by defualt OR at least process as an options.

**Comment by naugtur** [comment]
It would be incorrect for PUT. Otherwise a valid request, but

1. There's a package for that called `qs`. You can use it and concatenate the result to the url. We didn't include it as dependency because one of the core features of xhr is not increasing your browserify bundle size much
2. That wouldn't be compatible with request/request
