### ISSUE TITLE
Convenience APIs

### ISSUE THREAD

**Issue by wbinnssmith** [Raynos/xhr#96]
Hey! Love this module — it's awesome. I'm wondering if you're open to one or both of the following convenience APIs in the same vein as `request`:

* `xhr.post`, `xhr.put`, etc. as shortcuts for their respective methods.

* Providing a string as the first parameter as the url for the request, with options as they are provided as the second parameter.

This would enable requests like this:

```js
xhr.post("http://example.com", function (err, resp) {
  // ...
})
``` 

These would allow for more expressive xhr calls, though they'd introduce more than one way to do things and could slightly complicate this simple library with a magical API. IMHO this would be worth the tradeoff, but I thought I'd reach out before creating a PR or a wrapper library.

Thanks again.

**Comment by naugtur** [comment]
Node's request has them, so they could be done. The important thing to consider is if they should.
Xhr will not reach feature parity with other http requesting modules because it's supposed to be a lightweight one for including in independent libraries. 

Getting helpers implemented creates a risk of making a suggestion that we handle all the features.

But it's worth trying that.

I'd suggest waiting till we split xhr to remove old IE support to a separate module.

Then we can include a wrapper here as well.

**Comment by naugtur** [comment]
I've been busy and now I forgot where we left it. Make sure you're ok with my changes in branch and let me know if you changed anything since then.
I'd like to get down to merging it this week
